platform :ios, '7.0'

pod 'DFImageManager', '~> 0.5.0'
pod 'AFNetworking', '~> 2.0'
pod 'GoogleAnalytics'
pod 'Fabric'
pod 'Crashlytics', '~> 3.7.0'
pod 'MD5Digest', '~> 1.1'
pod 'RMStore', '~> 0.7'
pod 'RMStore/KeychainPersistence'
pod 'RMStore/NSUserDefaultsPersistence'
pod 'SSKeychain', '~> 1.3'